### ISSUE TITLE
Incompatible typescript version

### ISSUE THREAD

**Issue by michael-dean-haynie** [developerjaym/CodeCoffer#43]
**Describe the bug**
Error for incompatible typescript version is thrown when trying to run the app locally.

**To Reproduce**
1. Clone repo
2. Checkout master
3. Empty the npm cache: `npm cache clean -f`
4. Start application: `npm run start`
5. npm script fails to complete:
```bash
$ npm run start

> code-coffer@0.0.1 start /home/dean/Projects/CodeCoffer
> ng serve

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2019-11-08T00:59:50.013Z
Hash: 5575b1012022eda91df0
Time: 2490ms
chunk {main} main.js, main.js.map (main) 1.85 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 93.2 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 33.5 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.2.0 but 3.7.2 was found instead.
ℹ ｢wdm｣: Failed to compile.
```

**Expected behavior**
Instead of throwing an error, the npm script should complete successfully.

**Environment:**
- Ubuntu 18.04.3 LTS
- npm 6.13.0
- node v8.10.0

**Additional context**
Was not able to reproduce 100% of the time. Sometimes it works fine, sometimes it doesn't. Not sure what the changing variable is. Deleting the package-lock.json before the `npm install` may produce more consistent results.

**Comment by developerjaym** [comment]
I merged the PR. Marking as closed.
